#!/bin/bash
#
# ddRun: runs the program and stores the result in the output directory passed
# as argument

OUTDIR=$1

BIN=./vfcdd_champ
INP=input.inp
OUT=res

for i in $(seq 1 1); do 
	$BIN -i $INP -o /tmp/${OUT}.dat 2> ${OUTDIR}/ddrun.error
	awk '/total E/{print$4}' /tmp/${OUT}.dat > $OUTDIR/${OUT}$i.dat
	rm /tmp/${OUT}.dat
done

