#!/bin/bash
#
# ddRun: runs the program and stores the result in the output directory passed
# as argument

OUTDIR=$1

for i in $(seq 1 1); do 
	./vfcdd_champ -i input_with_wfopt.inp -o /tmp/res.dat 2> ${OUTDIR}/ddrun.error
	awk '/FORCE            1/{print$3}' /tmp/res.dat > $OUTDIR/res$i.dat
	rm /tmp/res.dat
done

